---
- name: Linux Post-Install Automation
  hosts: localhost
  become: yes
  tasks:

    - name: Update & Upgrade System
      apt:
        update_cache: yes
        upgrade: dist

    - name: Create User (if not exists)
      user:
        name: youruser
        shell: /bin/bash
        groups: sudo
        append: yes

    - name: Install Essential Packages
      apt:
        name:
          - git
          - curl
          - wget
          - unzip
          - zip
          - build-essential
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Enable and Start Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add User to Docker Group
      user:
        name: youruser
        groups: docker
        append: yes

    - name: Install Docker Compose
      shell: |
        curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
      creates: /usr/local/bin/docker-compose

    - name: Verify Docker Compose Installation
      command: docker-compose --version
      register: docker_compose_version
      changed_when: false

    - name: Install SSH Server
      apt:
        name: openssh-server
        state: present

    - name: Enable SSH Service
      systemd:
        name: ssh
        enabled: yes
        state: started

    - name: Install Python & Pip
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
        state: present

    - name: Upgrade Pip
      pip:
        name: pip
        state: latest

    - name: Install NVIDIA Drivers & CUDA
      apt:
        name:
          - nvidia-driver-535
          - nvidia-cuda-toolkit
        state: present

    - name: Reboot the machine
      reboot:
